"""New column addition in job_board c

Revision ID: 88cd42870e23
Revises: a011d4ab0d87
Create Date: 2025-11-24 16:31:33.144276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cd42870e23'
down_revision: Union[str, Sequence[str], None] = 'a011d4ab0d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_boards', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_boards', 'logo')
    # ### end Alembic commands ###
