"""New column addition in job_board

Revision ID: a011d4ab0d87
Revises: f9fc52e991c6
Create Date: 2025-11-24 16:28:27.716011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a011d4ab0d87'
down_revision: Union[str, Sequence[str], None] = 'f9fc52e991c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_boards', sa.Column('logo', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'job_boards', ['logo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_boards', type_='unique')
    op.drop_column('job_boards', 'logo')
    # ### end Alembic commands ###
