"""Job Application new table and Job post status column

Revision ID: b197ef06169e
Revises: 88cd42870e23
Create Date: 2025-11-25 15:57:57.324100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b197ef06169e'
down_revision: Union[str, Sequence[str], None] = '88cd42870e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('resume', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job_posts', sa.Column('job_post_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'job_post_status')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
