"""Foreign Key added and relashionship created

Revision ID: c673f82e8fa8
Revises: b197ef06169e
Create Date: 2025-11-26 10:22:04.356922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c673f82e8fa8'
down_revision: Union[str, Sequence[str], None] = 'b197ef06169e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'job_applications', 'job_posts', ['job_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    # ### end Alembic commands ###
