"""New job posts table is introduced

Revision ID: f9fc52e991c6
Revises: b7469802d4ea
Create Date: 2025-11-21 15:04:57.957039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fc52e991c6'
down_revision: Union[str, Sequence[str], None] = 'b7469802d4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('job_board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_board_id'], ['job_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posts')
    # ### end Alembic commands ###
